@startuml MDLExtension

' Definindo Estilos para MDL

skinparam componentStyle rectangle
skinparam monochrome false

' Definindo as cores padrões
skinparam default {
    BackgroundColor #FFFFFF
    BorderColor #1E90FF
    FontColor #1E90FF
    ArrowColor #1E90FF
}

' Definindo o estilo para Boundary
rectangle "boundary" as Boundary {
  skinparam {
    BorderColor #1E90FF
    FontColor #1E90FF
    BorderThickness 1
    BorderStyle dash
  }
}

' Definindo o estilo para Layer
rectangle "layer <<details>>" as Layer {
  skinparam {
    BackgroundColor White
    BorderColor #1E90FF
    FontColor #1E90FF
    Shadowing false
  }
}

' Definindo o estilo para Black Box
rectangle "black-box" as BlackBox {
  skinparam {
    BackgroundColor #1E90FF
    FontColor White
    BorderColor #1E90FF
  }
}

' Definindo o estilo para Front-end
component "front-end <<details>>" as FrontEnd {
  skinparam {
    BackgroundColor White
    BorderColor #1E90FF
    FontColor #1E90FF
    BorderThickness 1
  }
}

' Definindo o estilo para Back-end
component "back-end <<details>>" as BackEnd {
  skinparam {
    BackgroundColor White
    BorderColor #1E90FF
    FontColor #1E90FF
    BorderThickness 1
  }
}

' Definindo o estilo para Database
database "database <<details>>" as Database {
  skinparam {
    BackgroundColor White
    BorderColor #1E90FF
    FontColor #1E90FF
    BorderThickness 1
  }
}

' Estilo para Atores
skinparam actor {
    BackgroundColor White
    FontColor #1E90FF
    BorderColor #1E90FF
}

actor "Actor"

@enduml